### PR TITLE
Initial support for i18n

### PR DESCRIPTION
**Pull request by AlexMV12**
Hello, 

After the pull request https://github.com/sameera-madushan/SubtitleBOX/pull/8 I thought it could be nice to implement a localization for more than two languages. I have never done it, but it could by a nice way to learn.

I followed this guide, from the section "Message extraction": https://phrase.com/blog/posts/i18n-advantages-babel-python/ ; also, this other guide https://phrase.com/blog/posts/translate-python-gnu-gettext/

Also, I initiated the translations for english, turkish and italian (my language).
Let me know what you think; it would be nice if some expert in Python localization could help with this thing.

Have a nice day!

### CODE REVIEW

**Comment by sameera-madushan** [comment]
@AlexMV12  thank you for the PR. 
Same as you this is my first time dealing with localizing applications with gettext. 
Did you tested this on your end?

**Comment by AlexMV12** [comment]
Hello,
On my platform it is working and it recognizes correctly my locale.
I added a try/catch to fallback on English if the user locale is not recognized/not available.

Probably it should be tried on Windows, if you can.
Have a nice day

**Comment by sameera-madushan** [comment]
Finally i was able to test this and work perfectly on Linux boxes. But some conflicts arose and some of your code (in sbox.py file) got deleted while resolving the conflict. It would be great if could refactor it. Thanks for the understanding.

**Comment by AlexMV12** [comment]
Hello,
Now it should be okay.

I also added some comments, because the code is starting to get messy :) 
Eventually after this gets merge, I will try to do some more refactor otherwise it will be difficult to understand what's going on.

Goodbye

**Comment by sameera-madushan** [comment]
Thanks for the contribution ♥

**Comment by AlexMV12** [comment]
No problem! It's fun to contribute :)

**Comment by sameera-madushan** [comment]
hey @AlexMV12 
why did you commented this part 👇

# try:
#     user_locale = locale.getdefaultlocale()[0]
#     lang = gettext.translation('messages', localedir='locales', languages=[user_locale])
# except FileNotFoundError:

**Comment by AlexMV12** [comment]
Oops, sorry, my fault. I commented that to make some tests. You can uncomment that.

**Pull request merged**
